version: '1.12.2'
imports: []
mods:
- name: 'actually-additions'
- name: 'actually-baubles'
- name: 'ae2-stuff'
- name: 'ae2wtlib'
- name: 'akashic-tome'
- name: 'apotheosis'
- name: 'appleskin'
- name: 'applied-energistics-2'
- name: 'arcane-archives'
- name: 'architecturecraft-tridev'
- name: 'aroma1997core'
- name: 'aroma1997s-dimensional-world'
- name: 'astral-sorcery'
- name: 'autoreglib'
- name: 'astral-sorcery'
- name: 'bad-wither-no-cookie-reloaded'
- name: 'baubles'
- name: 'bdlib'
- name: 'bed-patch'
- name: 'better-builders-wands'
  maturity: beta
- name: 'betterfps'
- name: 'binnies-mods'
- name: 'biomes-o-plenty'
- name: 'blockcraftery'
- name: 'blood-magic'
- name: 'blur'
- name: 'bookshelf'
- name: 'botania'
- name: 'building-gadgets'
- name: 'cathedral'
- name: 'catwalks-4'
- name: 'cd4017be-library'
- name: 'chameleon'
- name: 'charm'
- name: 'charset-lib'
- name: 'chest-transporter'
- name: 'chisel'
- name: 'chisels-bits'
- name: 'chunkpregenerator'
- name: 'client-tweaks'
- name: 'climate-control-geographicraft'
- name: 'clipboard'
- name: 'clumps'
- name: 'codechicken-lib-1-8'
- name: 'cofh-core'
- name: 'cofh-world'
- name: 'colytra'
- name: 'comforts'
- name: 'common-capabilities'
- name: 'compact-machines'
- name: 'ctm'
- name: 'controlling'
- name: 'cooking-for-blockheads'
- name: 'cosmetic-armor-reworked'
- name: 'crafttweaker'
- name: 'custom-main-menu'
- name: 'deathquotes-death-quotes'
- name: 'deep-mob-learning'
- name: 'deep-resonance'
- name: 'default-options'
- name: 'ding'
- name: 'dynamic-surroundings'
- name: 'earthworks'
- name: 'eleccore'
- name: 'embers-rekindled'
- name: 'ender-io'
- name: 'ender-storage-1-8'
- name: 'endertweaker'
- name: 'endercore'
- name: 'engineers-doors'
- name: 'exchangers'
- name: 'fancy-lamps'
- name: 'farming-for-blockheads'
- name: 'fast-leaf-decay'
- name: 'faster-ladder-climbing'
- name: 'fastworkbench'
- name: 'flat-colored-blocks'
- name: 'foamfix-optimization-mod'
- name: 'forestry'
- name: 'forge-multipart-cbe'
- name: 'ftb-backups'
- name: 'ftblib'
- name: 'ftb-quests'
- name: 'ftb-utilities'
- name: 'game-stages'
- name: 'gravestone-mod'
- name: 'guide-api'
- name: 'immersive-cables'
- name: 'immersive-engineering'
- name: 'immersive-io'
- name: 'immersive-petroleum'
- name: 'immersiveposts'
- name: 'immersive-tech'
- name: 'initial-inventory'
- name: 'integrated-crafting'
- name: 'integrated-dynamics'
- name: 'integrated-terminals'
- name: 'integrated-tunnels'
- name: 'inventory-tweaks'
- name: 'iron-backpacks'
- name: 'item-filters'
- name: 'jei-bees'
- name: 'jei-integration'
- name: 'journeymap'
- name: 'jei'
- name: 'just-enough-petroleum'
- name: 'just-enough-resources-jer'
- name: 'kleeslabs'
- name: 'laggoggles'
- name: 'libraryex'
- name: 'llibrary'
- name: 'logistics-bridge'
- name: 'logistics-pipes'
- name: 'magic-bees'
- name: 'malisiscore'
- name: 'malisisdoors'
- name: 'mantle'
- name: 'mcjtylib'
- name: 'mcmultipart'
- name: 'mekanism'
- name: 'modelloader'
- name: 'modtweaker'
- name: 'modular-forcefield-system'
- name: 'modular-routers'
- name: 'more-overlays'
- name: 'morph-o-tool'
- name: 'morpheus'
- name: 'mouse-tweaks'
- name: 'mrtjpcore'
- name: 'mtlib'
- name: 'mystical-world'
- name: 'mysticallib'
- name: 'natures-compass'
- name: 'netherex'
- name: 'netherportalfix'
- name: 'not-enough-wands'
- name: 'notenoughids'
- name: 'nuclearcraft-mod'
- name: 'oc-xnet-driver'
- name: 'open-glider'
- name: 'opencomputers'
- name: 'orelib'
- name: 'p455w0rds-library'
- name: 'pams-harvestcraft'
- name: 'patchouli'
- name: 'phosphor'
- name: 'placebo'
- name: 'platforms'
- name: 'pneumaticcraft-repressurized'
- name: 'practical-logistics-2'
- name: 'prefab'
- name: 'pressure-pipes'
- name: 'psi'
- name: 'quark'
- name: 'railcraft'
- name: 'ranged-pumps'
- name: 'rats'
- name: 'reauth'
- name: 'reborncore'
- name: 'recipe-stages'
- name: 'redstone-arsenal'
- name: 'redstone-control'
- name: 'redstone-flux'
- name: 'rftools'
- name: 'rftools-control'
- name: 'roots'
- name: 'rustic'
- name: 'rustic-bop-woods'
- name: 'scannable'
- name: 'screenshot-to-clipboard'
- name: 'seed-drop'
- name: 'shadowfacts-forgelin'
- name: 'shadowmc'
- name: 'shetiphiancore'
- name: 'silent-gear'
- name: 'silent-lib'
- name: 'silents-gems'
- name: 'silents-gems-extra-parts'
- name: 'simple-ore-samples'
- name: 'simplelogic-gates'
- name: 'simplelogic-wires'
- name: 'simply-jetpacks-2'
- name: 'simply-light'
- name: 'smart-crafting-table'
- name: 'snad'
- name: 'sonar-core'
- name: 'soot'
- name: 'more-sound-config'
- name: 'steves-carts-reborn'
- name: 'storage-drawers'
- name: 'storage-drawers-extras'
- name: 'storage-drawers-unlimited'
- name: 'super-sound-muffler'
- name: 'swingthroughgrass'
- name: 'techreborn'
- name: 'tesla-core-lib'
- name: 'tetra'
- name: 'the-one-probe'
- name: 'thermal-dynamics'
- name: 'thermal-expansion'
- name: 'thermal-foundation'
- name: 'tipthescales'
- name: 'tis-3d'
- name: 'top-addons'
- name: 'torchmaster'
- name: 'totemic'
- name: 'unidict'
- name: 'wanionlib'
- name: 'waystones'
- name: 'wireless-crafting-terminal'
- name: 'wither-skeleton-tweaks'
- name: 'xnet'
- name: 'xtones'
- name: 'ynot'
- name: 'yungs-better-caves'
- name: 'zerocore'